/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

/**
 *
 * @author spook
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miCad = new javax.swing.JMenuItem();
        mEditar = new javax.swing.JMenu();
        miEdicao = new javax.swing.JMenuItem();
        mRemover = new javax.swing.JMenu();
        miRemocao = new javax.swing.JMenuItem();
        mPesquisar = new javax.swing.JMenu();
        miPesquisar = new javax.swing.JMenuItem();
        mCatalogo = new javax.swing.JMenu();
        miCat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Estoque");

        Menu.setToolTipText("");

        mCadastro.setText("Cadastro");
        mCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroActionPerformed(evt);
            }
        });

        miCad.setText("Cadastrar Produto");
        miCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadActionPerformed(evt);
            }
        });
        mCadastro.add(miCad);

        Menu.add(mCadastro);

        mEditar.setText("Edição");

        miEdicao.setText("Editar Produto");
        miEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEdicaoActionPerformed(evt);
            }
        });
        mEditar.add(miEdicao);

        Menu.add(mEditar);

        mRemover.setText("Remoção");

        miRemocao.setText("Remover Produto");
        miRemocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemocaoActionPerformed(evt);
            }
        });
        mRemover.add(miRemocao);

        Menu.add(mRemover);

        mPesquisar.setText("Pesquisa");

        miPesquisar.setText("Pesquisar produto");
        miPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPesquisarActionPerformed(evt);
            }
        });
        mPesquisar.add(miPesquisar);

        Menu.add(mPesquisar);

        mCatalogo.setText("Catálogo");

        miCat.setText("Catálogo de Produtos");
        miCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCatActionPerformed(evt);
            }
        });
        mCatalogo.add(miCat);

        Menu.add(mCatalogo);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroActionPerformed
        
    }//GEN-LAST:event_mCadastroActionPerformed

    private void miCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadActionPerformed
        DialogCadastro cad = new DialogCadastro(this, true);
        cad.setVisible(true);
    }//GEN-LAST:event_miCadActionPerformed

    private void miCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCatActionPerformed
        DialogCatalogo cat = new DialogCatalogo(this,true);
        cat.setVisible(true);
    }//GEN-LAST:event_miCatActionPerformed

    private void miEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEdicaoActionPerformed
        DialogEdicao edit = new DialogEdicao(this, true);
        edit.setVisible(true);
    }//GEN-LAST:event_miEdicaoActionPerformed

    private void miRemocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemocaoActionPerformed
        DialogRemocao rem = new DialogRemocao(this, true);
        rem.setVisible(true);
    }//GEN-LAST:event_miRemocaoActionPerformed

    private void miPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPesquisarActionPerformed
        DialogPesquisa pesq = new DialogPesquisa(this, true);
        pesq.setVisible(true);
    }//GEN-LAST:event_miPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mCatalogo;
    private javax.swing.JMenu mEditar;
    private javax.swing.JMenu mPesquisar;
    private javax.swing.JMenu mRemover;
    private javax.swing.JMenuItem miCad;
    private javax.swing.JMenuItem miCat;
    private javax.swing.JMenuItem miEdicao;
    private javax.swing.JMenuItem miPesquisar;
    private javax.swing.JMenuItem miRemocao;
    // End of variables declaration//GEN-END:variables
}
